name: Terraform pipeline

on:
  push:
    branches:
      - main
      - feature/*

env:
  AWS_REGION: us-east-1
  WORKING_DIR: ./network/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: terraform plan
      id: tf-plan
      run: |
          cd "${{ env.WORKING_DIR}}"
          terraform plan -detailed-exitcode -input=false
      continue-on-error: true

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan.outputs.exitcode }}
